version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: book_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwerty_17
      POSTGRES_DB: book_service
    ports:
      - "5432:5432"
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
